import type { Action, ActionResult, HandlerCallback, IAgentRuntime, Memory, State } from '@elizaos/core';
import { logger } from '@elizaos/core';
import { getCommunityMetrics } from './communityStats.ts';
import { getWeatherAssessment } from './checkWeather.ts';
import { getCurrentSeason, getSeasonalBriefing } from '../utils/seasonalAwareness.ts';
import { getSecurityLog } from '../security/sanitize.ts';
import { getTransactionHistory } from '../security/transactionGuard.ts';
import { getAllSubmissions } from '../submissions.ts';
import { getAllContractors } from '../providers/contractorReputation.ts';
import { sendDryadEmail } from './agentMail.ts';
import { getErrorMessage } from '../utils/fileErrors.ts';

const STEWARD_EMAIL = process.env.CONTRACTOR_EMAIL || 'powahgen@gmail.com';

type ReportType = 'weekly' | 'monthly';

function parseReportType(text: string): ReportType {
  if (/month/i.test(text)) return 'monthly';
  return 'weekly';
}

export async function generateWeeklyReport(): Promise<string> {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { timeZone: 'America/Detroit', month: 'long', day: 'numeric', year: 'numeric' });
  const season = getCurrentSeason();

  const [communityResult, weatherResult] = await Promise.allSettled([
    getCommunityMetrics(),
    getWeatherAssessment(),
  ]);

  const community = communityResult.status === 'fulfilled' ? communityResult.value : null;
  const communityError = communityResult.status === 'rejected' ? getErrorMessage(communityResult.reason) : null;
  const weather = weatherResult.status === 'fulfilled' ? weatherResult.value : null;
  const weatherError = weatherResult.status === 'rejected' ? getErrorMessage(weatherResult.reason) : null;

  const txHistory = getTransactionHistory();
  const secLog = getSecurityLog();
  const submissions = getAllSubmissions();
  const contractors = getAllContractors();

  const weekAgo = Date.now() - 7 * 86400000;
  const recentTx = txHistory.filter(t => t.timestamp > weekAgo);
  const recentSubs = submissions.filter(s => s.submittedAt > weekAgo);
  const injections = secLog.filter(e => e.event === 'INJECTION_ATTEMPT');
  const blockedTx = secLog.filter(e => e.event === 'TRANSACTION_BLOCKED');

  let report = `# Dryad Weekly Report\n`;
  report += `**${dateStr}** | **Season:** ${season.season} - ${season.description}\n\n`;

  if (weather) {
    report += `**Weather:** ${weather.summary}\n\n`;
  } else if (weatherError) {
    report += `**Weather:** unavailable (${weatherError})\n\n`;
  }

  report += `## Ecological Status\n`;
  if (community) {
    report += `- Species documented: ${community.speciesCount}\n`;
    report += `- Total observations: ${community.totalObservations} (${community.researchGradeObservations} research grade)\n`;
    if (community.mostRecent) {
      report += `- Most recent: ${community.mostRecent.species} by ${community.mostRecent.observer} (${community.mostRecent.date})\n`;
    }
  } else if (communityError) {
    report += `- Community data unavailable: ${communityError}\n`;
  } else {
    report += `- Community data unavailable this cycle\n`;
  }
  report += `- Seasonal note: ${season.priorities.slice(0, 2).join(', ')}\n\n`;

  report += `## Treasury\n`;
  const totalSpent = recentTx.reduce((s, t) => s + t.amount, 0);
  report += `- Transactions this week: ${recentTx.length} ($${totalSpent.toFixed(0)} total)\n`;
  report += `- All-time transactions: ${txHistory.length}\n\n`;

  report += `## Contractor Activity\n`;
  const active = contractors.filter(c => c.status === 'active');
  report += `- Active contractors: ${active.length}\n`;
  report += `- Registered: ${contractors.length} total\n`;
  if (active.length > 0) {
    for (const c of active) {
      report += `  - ${c.name}: ${c.jobsCompleted} jobs, reliability ${c.reliabilityScore}/100\n`;
    }
  }
  report += `\n`;

  report += `## Community Engagement\n`;
  if (community) {
    report += `- Unique observers: ${community.uniqueObservers}\n`;
    report += `- Photo submissions this week: ${recentSubs.length}\n`;
    report += `- Engagement trend: ${community.engagementTrend}\n`;
  }
  report += `\n`;

  report += `## Security\n`;
  report += `- Injection attempts: ${injections.length}\n`;
  report += `- Transactions blocked: ${blockedTx.length}\n`;
  report += `- Total security events: ${secLog.length}\n\n`;

  report += `## Next Steps\n`;
  for (const p of season.priorities.slice(0, 3)) {
    report += `- ${p}\n`;
  }
  if (active.length === 0 && season.season !== 'DORMANT') {
    report += `- **Priority:** Onboard contractors for ${season.contractorWorkTypes[0]}\n`;
  }
  report += `\n`;

  report += `---\n`;
  report += `Generated by Dryad (dryadforest.eth) | ERC-8004 #35293\n`;
  report += `${dateStr} | ${getSeasonalBriefing()}\n`;

  return report;
}

export const generateReportAction: Action = {
  name: 'GENERATE_REPORT',
  similes: ['WRITE_REPORT', 'STATUS_REPORT', 'WEEKLY_UPDATE', 'MONTHLY_REPORT', 'SEND_UPDATE'],
  description: 'Generate a periodic report on restoration progress, treasury, community engagement, and security. Can email to steward.',

  validate: async () => true,

  handler: async (
    _runtime: IAgentRuntime,
    message: Memory,
    _state: State,
    _options,
    callback: HandlerCallback,
    _responses: Memory[]
  ): Promise<ActionResult> => {
    try {
      const msgText = message.content.text || '';
      const reportType = parseReportType(msgText);
      const shouldEmail = /send|email|mail/i.test(msgText);

      logger.info(`[Dryad] Generating ${reportType} report`);
      const report = await generateWeeklyReport();

      if (shouldEmail) {
        try {
          const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
          await sendDryadEmail(
            STEWARD_EMAIL,
            `[Dryad] ${reportType === 'monthly' ? 'Monthly' : 'Weekly'} Report - ${dateStr}`,
            report
          );
          await callback({
            text: report + `\n\n✉️ Report emailed to ${STEWARD_EMAIL}`,
            actions: ['GENERATE_REPORT'],
            source: message.content.source,
          });
        } catch (emailErr) {
          await callback({
            text: report + `\n\n⚠️ Report generated but email failed: ${emailErr instanceof Error ? emailErr.message : String(emailErr)}`,
            actions: ['GENERATE_REPORT'],
            source: message.content.source,
          });
        }
      } else {
        await callback({ text: report, actions: ['GENERATE_REPORT'], source: message.content.source });
      }

      return {
        text: `${reportType} report generated`,
        values: { success: true, type: reportType, emailed: shouldEmail },
        data: {},
        success: true,
      };
    } catch (error) {
      const msg = `Report generation failed: ${error instanceof Error ? error.message : String(error)}`;
      await callback({ text: msg, actions: ['GENERATE_REPORT'], source: message.content.source });
      return { text: msg, values: { success: false }, data: {}, success: false };
    }
  },

  examples: [
    [
      { name: '{{name1}}', content: { text: 'Generate a weekly report' } },
      { name: 'Dryad', content: { text: "I'll compile this week's restoration progress, treasury status, and community engagement.", actions: ['GENERATE_REPORT'] } },
    ],
    [
      { name: '{{name1}}', content: { text: 'Send me a status update' } },
      { name: 'Dryad', content: { text: "Generating the report and emailing it to you.", actions: ['GENERATE_REPORT'] } },
    ],
  ],
};
